name: habit_tracker
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.15
  auto_route: ^9.2.2
  pin_code_fields: ^8.0.1
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.3
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  connectivity_plus: ^6.1.0
  android_id: ^0.4.0
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1


  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  retrofit_generator: ^9.1.5
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/habit_icons/


  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Semibold.ttf
          weight: 600

    - family: Unbounded
      fonts:
        - asset: assets/fonts/Unbounded-Medium.ttf
          weight: 500
