environment: 'local' # local/prod

auth:
  jwt:
    access_token_ttl: 1m
    refresh_token_ttl: 10m
    max_user_sessions: 5
    jwt_sign_key: 'fce9ee13dd03f63e21f86158e7b9cc79079886059d445ce7b0eca9ceceb88c76'

  hasher:
    hasher_salt: '363b420c9bd2a049219476f26ff9c031'

  email:
    email_from: 'ivan.kurochkin.084@gmail.com'
    email_password: 'hiqecckzffwewzqc'
    verif_code_ttl: 15m

http:
  host: '0.0.0.0'
  port: '8080'
  read_timeout: 5s
  write_timeout: 5s
  idle_timeout: 60s
  bytes_limit: 1024

postgresql:
  username: 'root'
  password: '12345'
  host: 'localhost' # localhost/postgresql
  port: '30000'     # 30000/5432
  database: 'habit_tracker'

