basePath: /v1
definitions:
  apperr.AppError:
    properties:
      code:
        type: string
      dev_message:
        type: string
      err_message:
        type: string
      user_message:
        type: string
    type: object
  v1.getVerifCodeRequest:
    properties:
      email:
        type: string
    type: object
  v1.loginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  v1.loginResponse:
    properties:
      jwt:
        type: string
    type: object
  v1.registerRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  v1.verifyCodeRequest:
    properties:
      code:
        type: string
      email:
        type: string
    type: object
  v1.verifyCodeResponse:
    properties:
      jwt:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: habit tracker API for mobile app
  title: Habit Tracker API
  version: "1.0"
paths:
  /auth/get-verification-code:
    post:
      consumes:
      - application/json
      description: send verification code to user's email
      parameters:
      - description: getVerifCode request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.getVerifCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK. Email with verification code was sent to user
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperr.AppError'
        "404":
          description: Not Found. User with provided email is not signing up
          schema:
            $ref: '#/definitions/apperr.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperr.AppError'
      summary: Get verification code
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: log user in
      parameters:
      - description: login request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK. User was logged in
          schema:
            $ref: '#/definitions/v1.loginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperr.AppError'
        "401":
          description: Unauthorized. Email or password is incorrect
          schema:
            $ref: '#/definitions/apperr.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperr.AppError'
      summary: Log user in
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: register new user
      parameters:
      - description: register request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.registerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK. Message was sent to user
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperr.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperr.AppError'
      summary: Register user
      tags:
      - auth
  /auth/verify-code:
    post:
      consumes:
      - application/json
      description: verify user's email by confirmation code
      parameters:
      - description: verify code request parameters
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.verifyCodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK. User was verified
          schema:
            $ref: '#/definitions/v1.verifyCodeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperr.AppError'
        "401":
          description: Unauthorized. User provided invalid verification code
          schema:
            $ref: '#/definitions/apperr.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperr.AppError'
      summary: Verify user's email
      tags:
      - auth
swagger: "2.0"
